name: Test and Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.11.24"
          enable-cache: true
      - name: Install the project
        run: uv sync --all-extras --dev

      # Install and run pre-commit
      - run: |
          uv run pre-commit install
          uv run pre-commit install --hook-type commit-msg
          uv run pre-commit run --all-files

  pytest:
    name: Pytest ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        config:
          - { name: "Linux", os: ubuntu-latest }
        # - {
        #     name: "MacOSX",
        #     os: macos-latest
        #   }
        # - {
        #     name: "Windows",
        #     os: windows-latest
        #   }

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.11.24"
          enable-cache: true

      - name: Set Up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Build Vue Components
        run: |
          cd vue-components
          npm i
          npm run build

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install OSMesa for Linux
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt-get install -y libosmesa6-dev

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
          source .venv/bin/activate
          playwright install
          pytest -s ./tests --cov=src --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-results-${{  matrix.config.name }}
          path: |
            tests/results/**/*.png
            tests/results/**/*.txt

          retention-days: 1

  test-npm-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set Up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Build Vue Components
        run: |
          cd vue-components
          npm i
          npm run build

  release:
    needs: [pre-commit, pytest, test-npm-build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment:
      name: pypi
      url: https://pypi.org/p/trame-vtklocal
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
      contents: write # IMPORTANT: mandatory for making GitHub Releases

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set Up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Build Vue Components
        run: |
          cd vue-components
          npm i
          npm run build

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.15.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package distributions to PyPI
        if: steps.release.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
